### ISSUE TITLE
v46 yanked some functions - intentional?

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1496] opened 2023-03-15 18:08 UTC
These functions were removed:

```
K32EmptyWorkingSet
K32EnumDeviceDrivers
K32EnumPageFilesA
K32EnumPageFilesW
K32EnumProcessModules
K32EnumProcessModulesEx
K32EnumProcesses
K32GetDeviceDriverBaseNameA
K32GetDeviceDriverBaseNameW
K32GetDeviceDriverFileNameA
K32GetDeviceDriverFileNameW
K32GetMappedFileNameA
K32GetMappedFileNameW
K32GetModuleBaseNameA
K32GetModuleBaseNameW
K32GetModuleFileNameExA
K32GetModuleFileNameExW
K32GetModuleInformation
K32GetPerformanceInfo
K32GetProcessImageFileNameA
K32GetProcessImageFileNameW
K32GetProcessMemoryInfo
K32GetWsChanges
K32GetWsChangesEx
K32InitializeProcessForWsWatch
K32QueryWorkingSet
K32QueryWorkingSetEx
```

**Comment by ChrisDenton** [comment] 2023-03-15 18:11
Presumably this is https://github.com/microsoft/win32metadata/issues/920#issuecomment-1466443444

**Comment by kennykerr** [comment] 2023-03-15 18:17
OK thanks. That means we'll have to bump the version of the `windows-targets` crate.

**Comment by mikebattista** [comment] 2023-03-15 18:17
Yes this is by design.

**Comment by riverar** [comment] 2023-03-30 15:08
Reopened this and the related https://github.com/microsoft/win32metadata/issues/920#issuecomment-1466443444. Will add my comments there.

**Comment by mikebattista** [comment] 2023-03-30 15:44
Duplicate of #920

**Closed by mikebattista** 2023-03-30 15:44 UTC
