### ISSUE TITLE
Various structs have invalid definitions due to confusing `Int64` with `IntPtr`

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1134] opened 2022-08-25 14:40 UTC
> Discrepancies where the numbers are different

Looks like these are also [win32metadata](https://github.com/microsoft/win32metadata) bugs. For example `CfDisconnectSyncRoot` is defined as follows in metadata:

```C#
public struct CF_CONNECTION_KEY
{
    public IntPtr Value;
}

public static extern HRESULT CfDisconnectSyncRoot([In] CF_CONNECTION_KEY ConnectionKey);
```

That explains why `windows-rs` says the stack size is 4 since `IntPtr` is 4 bytes on x86. 

But that's not accurate since the definition of `CF_CONNECTION_KEY` in the Windows SDK is always 8 bytes, regardless of architecture:

```C++
#define DECLARE_OPAQUE_KEY( name )          \
    typedef struct name##__ {               \
        LONGLONG Internal;                  \
    } name, *P##name

DECLARE_OPAQUE_KEY( CF_CONNECTION_KEY );
```

`LONGLONG` is just a typedef for `__int64`.

_Originally posted by @kennykerr in https://github.com/microsoft/windows-rs/issues/1985#issuecomment-1227351739_

**Comment by taufikrh** [comment] 2022-08-26 19:58
Not yet fixed #871

**Comment by kennykerr** [comment] 2022-08-26 20:34
Eek - we really should get this fixed.

**Comment by BenJKuhn** [comment] 2022-08-29 21:38
Duplicate of #871

**Closed by BenJKuhn** 2022-08-29 21:38 UTC
Labels: broken api, rust
