### ISSUE TITLE
Missing Privilege Constants from Winnt.h

### ISSUE THREAD

**Issue by roblabla** [microsoft/win32metadata#726] opened 2021-11-05 16:49 UTC
Winnt.h defines a bunch of constants starting by `SE_`. See https://docs.microsoft.com/en-us/windows/win32/secauthz/privilege-constants .

Those appear to be missing from the win32metadata. I believe it may be due to the use of the `TEXT` macro, as they are defined in the form:

```
#define SE_CHANGE_NOTIFY_NAME             TEXT("SeChangeNotifyPrivilege")
```

**Comment by mikebattista** [comment] 2021-11-05 18:01
Thanks. This is a dupe of #610.

**Closed by mikebattista** 2021-11-05 18:01 UTC
