### ISSUE TITLE
Provide metadata for error sentinel values returned by some Win32 APIs

### ISSUE THREAD

**Issue by talagrand** [microsoft/win32metadata#1551] opened 2023-04-26 00:26 UTC
This is a follow-up to https://github.com/microsoft/windows-rs/pull/2476#issuecomment-1522540893
Ideally, Win32 APIs that return a sentinel on failure would be annotated as such, so that the associated projection can implicitly handle these as error conditions.
Examples of such APIs: ExpandEnvironmentStringsW (returns 0 on failure) or ResumeThread (returns -1) or GlobalLock (returns NULL).

**Comment by mikebattista** [comment] 2023-04-26 07:12
Duplicate of #536

**Closed by mikebattista** 2023-04-26 07:12 UTC
