### ISSUE TITLE
Feature request: DirectStorage support

### ISSUE THREAD

**Issue by Jasper-Bekkers** [microsoft/win32metadata#1423] opened 2023-01-10 08:04 UTC
It looks like none of the DirectStorage (IDStorageQueue and friends) types are represented in this crate, it would be quite nice to have them supported.

**Comment by kennykerr** [comment] 2023-01-10 14:47
@damyanp may have more info on this API.

**Comment by riverar** [comment] 2023-01-10 16:02
Duplicate of https://github.com/microsoft/win32metadata/issues/836. I'll leave this open though for one of the owners to confirm whether they want to put this in win32metadata or not.

**Comment by damyanp** [comment] 2023-01-10 16:51
We don't currently have any plans to integrate the DirectStorage SDK into the Windows SDK, so this crate isn't the right place for it.

However, we do plan to generate and ship the winmd's through some other mechanism in the near future, but we're not quite ready to commit to a date for it.

**Comment by mikebattista** [comment] 2023-01-10 17:17
Thanks. Closing out in favor of producing metadata for this separately.

**Closed by mikebattista** 2023-01-10 17:17 UTC
Labels: enhancement
