### ISSUE TITLE
Structures with array[0] at end are incorrect

### ISSUE THREAD

**Issue by dorssel** [microsoft/win32metadata#1541] opened 2023-04-15 23:27 UTC
The following USB structures that were added with https://github.com/microsoft/win32metadata/issues/691 are created incorrectly:

USB_DESCRIPTOR_REQUEST
USB_NODE_CONNECTION_INFORMATION_EX

These have a flexible array as last member (e.g. UCHAR[0]). The structures as generated by CsWin32 have those last members as an array of size 1. As a consequence, the structures have the wrong size (e.g. using Unsafe.SizeOf<> or Marshal.SizeOf<>) and are therefore not usable.

See https://github.com/dorssel/usbipd-win/pull/583/files

**Comment by riverar** [comment] 2023-04-16 01:13
Related https://github.com/microsoft/win32metadata/issues/912.

**Comment by mikebattista** [comment] 2023-04-16 21:34
Duplicate of #912

**Closed by mikebattista** 2023-04-16 21:34 UTC
