### ISSUE TITLE
Investigate adding GDI+ APIs

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#1678] opened 2023-08-14 21:56 UTC
GDI+ is generally a collection of C++ classes but a flat API is available via `gdiplusflat.h` and impl. via `gdiplus.dll`.

We should take special note to use `#define GDIPVER 0x0110` to capture GDI+ version 1.1 APIs.

**Comment by mikebattista** [comment] 2023-08-14 23:57
Duplicate of #1287

**Closed by mikebattista** 2023-08-14 23:57 UTC

**Comment by riverar** [comment] 2023-08-15 04:29
@mikebattista oops, thanks!
