### ISSUE TITLE
OPENFILENAMEW Pack size is wrong, and can be omitted

### ISSUE THREAD

**Issue by MikeYeager** [microsoft/win32metadata#363] opened 2021-03-11 00:23 UTC
I'm pretty new to this, but I have some code using DllImport to call GetOpenFileName that works and I wanted to see if I could do it with CsWin32. The OPENFILENAMEW struct isn't very C# friendly, but shouldn't something like this work? The dialog doesn't even open.

```
        public static string MyGetOpenFileName()
        {
            var fileName = string.Empty;

            unsafe
            {
                fixed (char* file = new char[100])
                {
                    var request = new OPENFILENAMEW
                    {
                        lStructSize = (uint)sizeof(OPENFILENAMEW),

                        //lpstrInitialDir = null, 
                        //lpstrFilter = null,
                        //lpstrDefExt = null,

                        lpstrFile = new PWSTR(file),
                        nMaxFile = 100,

                        //hwndOwner = new HWND(),
                        //hInstance = new HINSTANCE(),
                        //Flags = 0,
                        //FlagsEx = 0,
                        //lpstrCustomFilter = null,
                        //lpstrTitle = null,
                        //lCustData = new LPARAM(),
                        //lpfnHook = null,
                        //lpstrFileTitle = null,
                        //lpTemplateName = null,
                        //nFileExtension = 0,
                        //nFileOffset = 0,
                        //nFilterIndex = 0,
                        //nMaxCustFilter = 0,
                        //nMaxFileTitle = 0,
                        //dwReserved = 0,
                        //pvReserved = null,
                    };

                    var s = request.lStructSize;

                    if (PInvoke.GetOpenFileName(ref request))
                        fileName = new string(request.lpstrFile);
                }
            }

            return fileName;
        }
```

**Comment by MikeYeager** [comment] 2021-03-16 17:40
Yes, it's 152 on my working version. I see the Pack =1 in the generated StructLayout attribute. Thanks for showing me the CommDlgExtendedError() trick! I hadn't thought of that. Still learning!

**Comment by sotteson1** [comment] 2021-03-17 04:35
Looks like I don't have _WIN64 defined. I thought I had been compiling for 64-bit but I guess not. But this makes me realize the structs will be different for x86 vs x64 compilations. Are we going to need both 32 and 64-bit versions of the metadata?

commdlg.h:

```C
#if !defined(_WIN64)
#include <pshpack1.h>         /* Assume byte packing throughout */
#endif
```

**Comment by kennykerr** [comment] 2021-03-17 13:00
I'd very much prefer a single winmd. Perhaps we can have an attribute on those structs that have arch-specific layout and then each field can have a arch attribute, either 64 or 32. You can then aggregate up the fields for each architecture. Similar to how we declare explicit layout.

**Comment by AArnott** [comment] 2021-03-17 15:14
Some structs vary more significantly than just their Pack attribute between their 32-bit and 64-bit variants. Some structs add fields for a subset of architectures. We may need to consider ARM or other architectures as potentially impactful too rather than just based on pointer size.

My primary requirement is that the projections can trivially discern between a struct that is truly "AnyCPU" vs one that requires different definitions per architecture, so that we can emit the AnyCPU code in C# freely, but once an architectural-dependent struct is generated we can error out if the user hasn't split to targeting specific architectures.

**Comment by kennykerr** [comment] 2021-03-17 15:32
There are already many structs that have 32 bit and 64 bit variants. Things like `TRACE_LOGFILE_HEADER`/`TRACE_LOGFILE_HEADER32`/`TRACE_LOGFILE_HEADER64` and `IMAGE_OPTIONAL_HEADER32`/`IMAGE_OPTIONAL_HEADER64`, and so on. For those that just have them hidden behind a `defined(_WIN64)` we could just produce pairs of X32/X64 struct definitions.

**Comment by AArnott** [comment] 2021-03-17 15:42
True: when the structs have unique names in the headers, mirroring that in the metadata is fine.
But where the structs have the same name but different content or pack details in the headers, I think we should keep the same name in the metadata to match.

**Comment by kennykerr** [comment] 2021-03-17 16:28
This just seems like a simple solution to the problem. The headers depend on preprocessor macros while the metadata obviously does not. There is also evidence that this is precisely the reason these 32/64 structs were introduced in the first place. For example:

```C++
// TRACE_LOGFILE_HEADER32 and TRACE_LOGFILE_HEADER64 structures
// are also provided to simplify cross platform decoding of the
// header event.
```

It is quite common to depend on these explicitly-sized structs for parsing and cross-process memory access. So following this example seems to make sense in cases where there is no platform-agnostic way to define a struct.

**Comment by AArnott** [comment] 2021-03-17 16:42
@kennykerr, are you suggesting that in cases where the headers do _not_ have unique names per architecture that we always create structs with unique names per architecture in the metadata?

What if _every_ struct has to be split only because the Pack parameter is different?

Which of the 2+ structs should be referenced in all the APIs that take what used to be just one struct? Any choice will make all the other structs much harder to pass in (for a strongly typed language like C#). That seems like a non-starter, IMO.

**Comment by kennykerr** [comment] 2021-03-17 16:49
> Are you suggesting that in cases where the headers do not have unique names per architecture that we always create structs with unique names per architecture in the metadata?

Yes

> What if every struct has to be split only because the Pack parameter is different?

That's not the case in practice.

> Which of the 2+ structs should be referenced in all the APIs that take what used to be just one struct? 

We could have a marker struct (like we do for handles/typedefs) that uses the friendly name and has attributes for different architectures. 

It would be useful to understand how much of a problem this is and have some practical examples to play with. This approach may indeed be impractical, but at least the structs I've looked at this seems practical enough. 

What would you suggest?

**Comment by kennykerr** [comment] 2021-03-17 17:25
Another gem I've used before is `MEMORY_BASIC_INFORMATION` also in winnt.h ...

**Comment by sotteson1** [comment] 2021-03-24 06:42
Fixed by changing the metadata to be built for 64-bit. We need a 32-bit strategy, though.

**Closed by sotteson1** 2021-03-24 06:42 UTC
Labels: broken api

**Comment by kennykerr** [comment] 2021-03-24 13:54
Duplicate of #384
