### ISSUE TITLE
SetWindowLongPtr/GetWindowLongPtr are missing

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#142] opened 2021-01-21 14:08 UTC
@defaultRyan said in #141:

> Windows.Win32.MenuRc.Apis.SetWindowLongW
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowlongptrw
This function (both the A and W variants, along with GetWindowLongW) has a different definition appear for 32-bit and 64-bit fields:

The mentioned SetWindowLongPtr/GetWindowLongPtr methods (A and W variants) are missing from the metadata.

How should we represent the LongPtr version in metadata, considering only the 64-bit version is exported and the other is a macro? An attribute?

**Comment by kennykerr** [comment] 2021-01-26 20:33
`SetWindowLongPtrW`, `SetWindowLongPtrA`, `GetWindowLongPtrW`, and `GetWindowLongPtrA` are regular functions. We need those added to metadata.

**Comment by AArnott** [comment] 2021-02-05 15:59
@kennykerr I don't think `GetWindowLongPtrA`/`GetWindowLongPtrW` are in fact regular functions in 32-bit apps. I agree with @DefaultRyan and here is evidence:

```
❯ dumpbin /exports C:\windows\SysWOW64\user32.dll | findstr /i GetWindowLongPtr
andarno@RYZEN9  ~\source\repos                                                                               [08:56]
❯ dumpbin /exports C:\windows\system32\user32.dll | findstr /i GetWindowLongPtr
       1992  1E7 00010DE0 GetWindowLongPtrA
       1993  1E8 0000F830 GetWindowLongPtrW
```

See how the functions are only exported from the 64-bit dll? That would explain why the header file maps the function names to their 32-bit counterparts via a `#define` macro. If we p/invoke to these methods blindly, they will fail in 32-bit processes. We need to do something more clever here.

**Comment by kennykerr** [comment] 2021-02-05 17:00
Oh, I see what you're saying. They are regular functions but only for 64-bit architectures. For 32-bit architectures, the Windows SDK defines them as follows:

```
#define GetWindowLongPtrA   GetWindowLongA
#define SetWindowLongPtrA   SetWindowLongA
```

These are just equivalent functions that provide 32-bit rather than 64-bit values as part of their signatures. But the function names are different to ensure loaders and linkers target the appropriate export.

In that case, I think it's reasonable to exclude them from metadata.

**Comment by AArnott** [comment] 2021-02-05 21:26
> I think it's reasonable to exclude them from metadata.

 shouldn't there be a way to call these functions from a 64-bit process?

**Comment by kennykerr** [comment] 2021-02-05 23:20
Sure, we could have some attribute that indicates that the function only supports a specific architecture. Happy to adopt something like that.

I just mean that I don't have a problem if we simply want to exclude corner cases like this and let someone wanting to call it to just go and declare it themselves.

**Comment by marler8997** [comment] 2021-02-09 21:41
I ran into this issue today.  I'd vote for inclusion of these function in the metadata, with something to mark them as 64-bit only.

**Comment by timsneath** [comment] 2021-02-14 04:39
I hit this while trying to build a Dart projection out of metadata, and I'd like to vote that this is included in the metadata. The [documentation explicitly tells](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowlongptrw) Windows developers to use this, so it's a pain that this isn't included in the metadata.

Maybe you have data suggesting otherwise, but I'm assuming that the intersect of Windows 10 and 32-bit is small and diminishing and that the 64-bit user is the primary audience for this. Even though I'm supporting Windows 7 for my projection, 32-bit is a best-effort endeavor from my side and I'm thinking of dropping it.

**Comment by marler8997** [comment] 2021-02-14 05:51
@timsneath To make sure we are on the same page, this is roughly what is trying to be represented:

```c
#if WIN64
    uint32 SetWindowLongPtr(...);
    int64 GetWindowLongPtr(...);
#else // WIN32
    #define SetWindowLongPtr SetWindowLong
    #define GetWindowLongPtr GetWindowLong
#endif
```

So, these functions are defined normally on 64-bit, and on 32-bit they are missing from the dll and are actually defined as aliases to other functions that do exist in the dll.  So as it stands, win32metadata needs 2 additional features to represent this.

1. A way to differentiate 64-bit and 32-bit definitions
2. A way to define function aliases

So I was questioning how much benefit we get by adding these 2 new features to the metadata if its only for this one case.  Different story if there are more cases that would use these features.  I suspect there will be more differences between 32/64 bit.  I'm not as confident there are more function alias cases, maybe someone can enlighten us?

**Comment by kennykerr** [comment] 2021-02-14 05:55
The macros aren't import but the APIs are and there are indeed other important APIs that fall in this same category so we will likely add an architecture attribute for this.

**Comment by AArnott** [comment] 2021-02-18 16:27
We definitely need no. 1 from @marler8997's list. There are other APIs that are different between the two architectures.
Ideally we have no. 2 as well.

**Comment by kennykerr** [comment] 2021-03-24 15:45
Duplicate of #384

**Comment by kennykerr** [comment] 2021-03-25 13:11
These functions are now present. We can probably close this issue.

**Comment by timsneath** [comment] 2021-03-25 16:05
Awesome. I want to just give you guys kudos, @sotteson1 in particular -- you're doing a fantastic job at cranking through these issues and turning them around quickly! Thank you. It builds a ton of confidence on my side.

**Closed** 2021-03-25 16:47 UTC
Labels: missing api

**Comment by marler8997** [comment] 2021-03-30 03:20
Correct me if I'm wrong but it appears that these functions have been added to the metadata without providing a way to differentiate 64-bit and 32-bit definitions, which is a problem because these functions don't exist on 32-bit versions of the user32.dll.  This means users will get linker errors when compiling for i386.

**Comment by sotteson1** [comment] 2021-03-30 03:21
> Correct me if I'm wrong but it appears that these functions have been added to the metadata without providing a way to differentiate 64-bit and 32-bit definitions, which is a problem because these functions don't exist on 32-bit versions of the user32.dll. This means users will get linker errors when compiling for i386.

Yes, there's an issue I'm going to work on this week to address that: #384
