### ISSUE TITLE
Feature request: Bitfield setter and getter

### ISSUE THREAD

**Issue by ANOLASC** [microsoft/win32metadata#1475] opened 2023-02-23 10:20 UTC
### Motivation

Structs like MEM_EXTENDED_PARAMETER which have bitfield member is hard to be accessed and modified.

Original definition
```C++
typedef struct MEM_EXTENDED_PARAMETER {
  struct {
    DWORD64 Type : MEM_EXTENDED_PARAMETER_TYPE_BITS;
    DWORD64 Reserved : 64 - MEM_EXTENDED_PARAMETER_TYPE_BITS;
  } DUMMYSTRUCTNAME;
  union {
    DWORD64 ULong64;
    PVOID   Pointer;
    SIZE_T  Size;
    HANDLE  Handle;
    DWORD   ULong;
  } DUMMYUNIONNAME;
} MEM_EXTENDED_PARAMETER, *PMEM_EXTENDED_PARAMETER;
```
Rust definition
```Rust
pub struct MEM_EXTENDED_PARAMETER {
    pub Anonymous1: MEM_EXTENDED_PARAMETER_0,
    pub Anonymous2: MEM_EXTENDED_PARAMETER_1,
}

pub struct MEM_EXTENDED_PARAMETER_0 {
    pub _bitfield: u64,
}
```
Currently Rust does not support bitfields. It is cumbersome, clumsy and error-prone that when I try to pass a struct like ```MEM_EXTENDED_PARAMETER ``` to ``` VirtualAlloc ```.
I think provide interfaces like 
```Rust
pub fn set_type();
pub fn get_type();
pub fn set_reserved();
pub fn get_reserved();
```
would be easier to use this struct

**Comment by mikebattista** [comment] 2023-02-23 19:05
I believe this is a duplicate of #1392.

**Closed by mikebattista** 2023-02-23 19:05 UTC
Labels: enhancement
