### ISSUE TITLE
IDCompositionVisual2::SetOffsetX methods are flipped in SDK + metadata

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#600] opened 2021-08-03 18:03 UTC
Related: https://github.com/microsoft/windows-rs/issues/1017
SDKs tested: 19041, 22000
Header: dcomp.h

From header:
```cpp
DECLARE_INTERFACE_IID_(IDCompositionVisual, IUnknown, "4d93059d-097b-4651-9a60-f0f25116e2f3")
{
    // Changes the value of OffsetX property
    STDMETHOD(SetOffsetX)(THIS_
        float offsetX
        ) PURE;

    // Animates the value of the OffsetX property.
    STDMETHOD(SetOffsetX)(THIS_
        _In_ IDCompositionAnimation* animation
        ) PURE;

    // ...
```

Actual (debugger, OS 19043.1110):
```diff
0:001> dps dcomp!Windows::UI::Composition::InteropVisual::Api::`vftable'
 00007ff8`4ddd6c20  00007ff8`4dcc2390 dcomp![...]::QueryInterface
 00007ff8`4ddd6c28  00007ff8`4dcd8f00 dcomp![...]::AddRef
 00007ff8`4ddd6c30  00007ff8`4dcbe6f0 dcomp![...]::Release
-00007ff8`4ddd6c38  00007ff8`4dd61980 dcomp!Windows::UI::Composition::InteropVisual::Api::SetOffsetX
//                  ^^^^^^^^^^^^^^^^^ slot 3 = SetOffsetX(IDCompositionAnimation*)
 00007ff8`4ddd6c40  00007ff8`4dcce450 dcomp!Windows::UI::Composition::InteropVisual::Api::SetOffsetX
 00007ff8`4ddd6c48  00007ff8`4dd61a20 dcomp!Windows::UI::Composition::InteropVisual::Api::SetOffsetY
 00007ff8`4ddd6c50  00007ff8`4dc96d00 dcomp!Windows::UI::Composition::InteropVisual::Api::SetOffsetY
 00007ff8`4ddd6c58  00007ff8`4dccf970 dcomp!Windows::UI::Composition::InteropVisual::Api::SetTransform
 00007ff8`4ddd6c60  00007ff8`4dd61de0 dcomp!Windows::UI::Composition::InteropVisual::Api::SetTransform
 00007ff8`4ddd6c68  00007ff8`4dd61fe0 dcomp!Windows::UI::Composition::InteropVisual::Api::SetTransformParent
 00007ff8`4ddd6c70  00007ff8`4dcd15e0 dcomp!Windows::UI::Composition::InteropVisual::Api::SetEffect
 00007ff8`4ddd6c78  00007ff8`4dcd5c30 dcomp!Windows::UI::Composition::InteropVisual::Api::SetBitmapInterpolationMode
 00007ff8`4ddd6c80  00007ff8`4dcd6850 dcomp!Windows::UI::Composition::InteropVisual::Api::SetBorderMode
 00007ff8`4ddd6c88  00007ff8`4dd617a0 dcomp!Windows::UI::Composition::InteropVisual::Api::SetClip
 00007ff8`4ddd6c90  00007ff8`4dcd4690 dcomp!Windows::UI::Composition::InteropVisual::Api::SetClip
 00007ff8`4ddd6c98  00007ff8`4dcc85f0 dcomp!Windows::UI::Composition::InteropVisual::Api::SetContent
0:001> x /v dcomp!Windows::UI::Composition::InteropVisual::Api::SetOffsetX*
 prv func   00007ff8`4dcce450   6c dcomp!Windows::UI::Composition::InteropVisual::Api::SetOffsetX (void)
-pub func   00007ff8`4dd61980    0 dcomp!Windows::UI::Composition::InteropVisual::Api::SetOffsetX (public: virtual long __cdecl Windows::UI::Composition::InteropVisual::Api::SetOffsetX(struct IDCompositionAnimation *))
//          ^^^^^^^^^^^^^^^^^
```

**Comment by riverar** [comment] 2021-08-04 20:38
Adding binding authors for awareness @AArnott @kennykerr @timsneath @rumbu13 @marler8997

**Comment by kennykerr** [comment] 2021-08-06 16:24
Technically, this is a bug in the original `IDCompositionVisual` definition itself. COM interface vtable ordering is not stable in the face of method overloading and is not guaranteed to work reliably. WinRT interface interfaces overcome this by giving the overloaded methods unique ABI names, but this is not a WinRT interface. 

If the C++ compiler ends up sorting them differently in practice (e.g. the `IDCompositionAnimation*` overload appears before the `float` overload) then the Win32 metadata should probably reflect that. This is a case where the metadata would need to manually fix up this definition to reflect the reality on the ground.

**Comment by KalleOlaviNiemitalo** [comment] 2021-08-06 16:46
If you include \<dcomp.h> in C (or in C++ while defining `CINTERFACE`), then each `STDMETHOD` becomes a data member, so their ordering will surely match what the IDL compiler generated. I suppose the interface is then broken in this kind of use, too.

**Comment by jeffstall** [comment] 2021-08-06 17:19
For better of for worse, the C++ compiler puts overloaded interface members in reverse declaration order in the vtable. So SetOffsetX(IDCompositionAnimation *) will be before SetOffsetX(float). Any Win32 metadata compiler will need to do the same thing. (Even if teams did this unintentionally, they still can't change the definition as it would be a breaking change.)

@mikebattista , can you please redirect to the metadata team?

**Comment by mikebattista** [comment] 2021-08-06 17:22
Thanks. Assigning to Steve to work around this in the metadata.

**Comment by riverar** [comment] 2021-08-23 20:25
@sotteson1 Yep. And SetTransform, SetClip, etc.

**Comment by kennykerr** [comment] 2021-08-23 20:28
What about overloads in a hierarchy? IThing3 overloads a method in IThing2? 

What about three or more overloads? Is it strictly in-place reverse order?

**Comment by sotteson1** [comment] 2021-08-23 20:30
And another question like @kennykerr is asking: what if I have something like this:

````C
SetOffsetX(float)
Foo()
SetOffsetX(IDCompositionAnimation*)
````
What would that look like in the vtable?

**Comment by jeffstall** [comment] 2021-08-23 20:35
At the end of the day, I'd recommend writing a bunch of conformance tests with the VC++ compiler.

**Comment by riverar** [comment] 2021-08-24 07:30
@sotteson1 I did a quick query for all interfaces that have overloaded members. Unless I missed something, this only seems to impact a few namespaces. Are you seeing similar results? I'd say we could just knock this out manually but seeing new teams making the same _mistake_ suggests this pattern will continue and you'll need to automate this.

Namespaces (5):
```
Windows.Win32.Graphics.Direct2D
Windows.Win32.Graphics.DirectComposition
Windows.Win32.Graphics.DirectWrite
Windows.Win32.Data.HtmlHelp
Windows.Win32.AI.MachineLearning.WinML
```

Interfaces (36):
```
ID2D1SvgStrokeDashArray
ID2D1SvgElement
IDCompositionVisual
IDCompositionTranslateTransform
IDCompositionScaleTransform
IDCompositionRotateTransform
IDCompositionSkewTransform
IDCompositionMatrixTransform
IDCompositionEffectGroup
IDCompositionTranslateTransform3D
IDCompositionScaleTransform3D
IDCompositionRotateTransform3D
IDCompositionMatrixTransform3D
IDCompositionRectangleClip
IDCompositionVisual3
IDCompositionGaussianBlurEffect
IDCompositionBrightnessEffect
IDCompositionColorMatrixEffect
IDCompositionShadowEffect
IDCompositionHueRotationEffect
IDCompositionSaturationEffect
IDCompositionLinearTransferEffect
IDCompositionTableTransferEffect
IDCompositionArithmeticCompositeEffect
IDCompositionAffineTransform2DEffect
IDWriteFactory3
IDWriteFontSet
IDWriteFontSetBuilder
IDWriteGdiInterop1
IDWriteFontFace4
IDWriteFactory4
IDWriteFontSet1
IITPropList
IITWordWheel
IITResultSet
IMLOperatorKernelContext
```

Interesting interfaces (and associated header file(s)) from test scenario authoring POV:
* `ID2D1SvgElement` - 3 methods (SetAttributeValue) [interweaved](https://github.com/microsoft/win32metadata/issues/600#issuecomment-904100797)
* `ID2D1SvgStrokeDashArray` - 2 methods, back to back
* `IDWriteFontSetBuilder1/2` - Inheritance fun, both have `AddFontFile`
* `IITPropList` (`infotech.h`) - 3 methods, vanilla

**Comment by kennykerr** [comment] 2021-08-24 16:55
@jonwis may want to look out for this in API review going forward as its quite a compatibility issue.

**Comment by sotteson1** [comment] 2021-08-24 18:01
Thanks for the research @riverar. I should be able to come up with a programmatic way to fix these so we don't have to manually fix them.

**Closed** 2021-09-27 21:53 UTC
Labels: broken api

**Comment by smourier** [comment] 2021-11-19 09:37
Hi,

I know this is a closed issue, I just arrived here searching about that strange vtable overload inversion "thing".

Just curious: is there any C++ compiler reference, standard of document that confirms this "inversion" behavior?
And is this only for MSVC?

The only thing I found about this is here: https://stackoverflow.com/questions/61542063/inversion-of-generated-vtable-functions-order-for-functions-with-the-same-name but it's not entirely satisfying.

Thanks.

**Comment by FactoryXCode** [comment] 2022-02-22 23:03
The issue is not a compiler issue, but a wrong method sequence in the headerfile (interface declaration). This is exactly the same issue reported [here](https://docs.microsoft.com/en-us/answers/questions/61930/wrong-method-sequence-in-id2d1svgelement-api.html)
