### ISSUE TITLE
HtmlHelp API is marked with the wrong dll

### ISSUE THREAD

**Issue by JeremyKuhne** [microsoft/win32metadata#1799] opened 2024-01-08 19:53 UTC
`HtmlHelpW` and `HtmlHelpA` are shown as coming from `htmlhelp.dll`. They actually are in `hhctrl.ocx` as documented  https://learn.microsoft.com/windows/win32/api/htmlhelp/nf-htmlhelp-htmlhelpw.

**Comment by riverar** [comment] 2024-01-08 20:09
Duplicate of #1749, fixed via #1752, should be in the next release!

**Closed by riverar** 2024-01-08 20:09 UTC

**Comment by JeremyKuhne** [comment] 2024-01-08 20:38
Sorry, didn't see the other when I searched. :)

**Comment by riverar** [comment] 2024-01-08 20:41
@jeremykuhne No problem whatsoever, when it doubt feel free to file.
