### ISSUE TITLE
Support variadic functions

### ISSUE THREAD

**Issue by dpaoliello** [microsoft/win32metadata#493] opened 2021-05-20 21:25 UTC
Currently the `...` param of variadic functions is getting dropped (i.e., it is not represented in the metadata at all).

For example `IDebugControl::ControlledOutput` (https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/dbgeng/nf-dbgeng-idebugcontrol-controlledoutput) is variadic. But the metadata doesn't show this at all:
```
.method public hidebysig newslot abstract virtual 
        instance valuetype Windows.Win32.System.Com.HRESULT 
        ControlledOutput([in] uint32 OutputControl,
                         [in] uint32 Mask,
                         [in] valuetype Windows.Win32.System.SystemServices.PSTR Format) cil managed
{
  .param [3]
  .custom instance void [Windows.Win32.Interop]Windows.Win32.Interop.ConstAttribute::.ctor() = ( 01 00 00 00 ) 
} // end of method IDebugControl::ControlledOutput
```

Given that the metadata format is based on MSIL, perhaps it can be represented like a C# `params` parameter?

**Comment by mikebattista** [comment] 2021-05-20 23:07
Thanks. Yes, I believe this is a dupe of #33 .

**Closed** 2021-05-20 23:10 UTC
