### ISSUE TITLE
VirtualQueryEx check return != 0

### ISSUE THREAD

**Issue by kgv** [microsoft/win32metadata#1135] opened 2022-08-26 04:36 UTC
Should the check `_Success_(return != 0)` be added for `VirtualQueryEx`?

docs:
> If the function fails, the return value is zero.

**Comment by riverar** [comment] 2022-09-22 03:17
What are you suggesting be added? Not sure I understand.

**Comment by kgv** [comment] 2022-09-23 07:33
@riverar 
Add `_Success_(return != 0)` before [this line](https://github.com/microsoft/win32metadata/blob/f86785bec72eef8aa9c9cf5a84fc6d446abe2db5/generation/WinSDK/RecompiledIdlHeaders/um/memoryapi.h#L141).

**Comment by riverar** [comment] 2022-09-23 16:05
@mikebattista What do you want to do with SDK feedback/requests like this?

**Comment by mikebattista** [comment] 2022-09-23 16:09
Is there a metadata equivalent for this scenario? Don't we use PreserveSig for "alternative success codes"?

**Comment by riverar** [comment] 2022-09-23 16:20
@mikebattista Don't think we do anything with this SAL annotation at this time in metadata. Believe this is SDK headers feedback.

Here's `VirtualProtectEx` (with _Success_):
```csharp
[DllImport("KERNEL32.dll", ExactSpelling = true, PreserveSig = false, SetLastError = true)]
[SupportedOSPlatform("windows5.1.2600")]
public unsafe static extern BOOL VirtualProtectEx(...);
```

And here's `VirtualQueryEx` (without _Success_)
```csharp
[DllImport("KERNEL32.dll", ExactSpelling = true, PreserveSig = false, SetLastError = true)]
[SupportedOSPlatform("windows5.1.2600")]
public unsafe static extern UIntPtr VirtualQueryEx(...);
```

**Comment by mikebattista** [comment] 2022-09-23 16:24
What does the ideal metadata look like for this scenario regardless of SAL annotations?

**Comment by mikebattista** [comment] 2022-11-03 20:16
@kennykerr what are your thoughts on this? How should this API be decorated given the recent changes to our CanReturn attributes?

**Comment by kennykerr** [comment] 2022-11-03 20:28
Sorry, I don't know what the problem is. The original issue seems to be a complaint about the original Windows header definition which seems out of scope for this project.

**Comment by kennykerr** [comment] 2022-11-03 20:29
And the `CanReturn...` attributes are meant for APIs that return an error code or type like `HRESULT` or `BOOL` and `VirtualQueryEx` is not such an API.

**Comment by mikebattista** [comment] 2022-11-03 20:31
This API returns 0 on failure, otherwise it returns the actual number of bytes returned in the information buffer. This is defined as SIZE_T in the headers which translates to UIntPtr today. Do we need a change here?

**Comment by kennykerr** [comment] 2022-11-03 20:33
The metadata representation seems adequate to me.

**Comment by mikebattista** [comment] 2022-11-03 20:35
Ok. Closing out then. I don't see a need to change the original headers either.

**Closed by mikebattista** 2022-11-03 20:35 UTC
Labels: enhancement

**Comment by riverar** [comment] 2022-11-03 20:47
This was SDK feedback, particularly a request to add a missing SAL annotation in the original headers. I suspect they filed the issue here because the SDK team has no other feedback channel. (That's why I asked [this question](https://github.com/microsoft/win32metadata/issues/1135#issuecomment-1256397936).)

**Comment by mikebattista** [comment] 2022-11-03 20:53
There are plenty of issues with the original headers that have been around forever and aren't a priority to fix. If we can improve usability via the metadata, then we should, but that doesn't seem to be the case here.
