### ISSUE TITLE
Regression in PolyDraw API

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#346] opened 2021-03-14 02:00 UTC
This is defined as:

```c
BOOL PolyDraw(
  HDC         hdc,
  const POINT *apt,
  const BYTE  *aj,
  int         cpt
);
```

but is now being projected as 

```csharp
[DllImport("GDI32", ExactSpelling = true)]
public unsafe static extern BOOL PolyDraw(
  [In] HDC hdc, 
  [In][Const][NativeArrayInfo(SizeParamIndex = 3)] POINT* apt, 
  [In][Const][NativeArrayInfo(SizeParamIndex = 3)] GetPath_aj aj, 
  [In] int cpt);
```

Note that aj is no longer a `Pointer`, but defined as:

```csharp
public enum GetPath_aj : uint
{
	PT_MOVETO = 6u,
	PT_LINETO = 2u,
	PT_BEZIERTO = 4u
}
```

**Comment by timsneath** [comment] 2021-03-14 02:13
Same for `GetScrollInfo` and `SetScrollInfo`, which should take a `Pointer<SCROLLINFO>` as a parameter, and `LoadIcon`, which should take an `LPCWSTR` as the second parameter, rather than an `int`. These all worked in the winmd file I generated about a week ago, but have regressed at some point since then.

**Comment by sotteson1** [comment] 2021-03-15 07:33
The scraper has misinterpreted the docs in this case. It should not have gotten rid of the pointer.

**Comment by mikebattista** [comment] 2021-03-15 17:09
@sotteson1 is this a dupe of #337 or a separate issue?

**Comment by sotteson1** [comment] 2021-03-22 18:25
This is now fixed.

**Closed by sotteson1** 2021-03-22 18:25 UTC
Labels: broken api
