### ISSUE TITLE
Double pointers to strings have no NativeTypeInfo

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#241] opened 2021-02-16 05:29 UTC
`ShGetKnownFolderPath` returns a `Pointer<Pointer<Utf16>>` in my existing (non-metadata based) projection, but the Win32 metadata shows it as returning a `Pointer<Pointer<Uint16>>` because there's no `NativeTypeInfo` attribute for `ppszPath`.

```c
HRESULT SHGetKnownFolderPath(
  REFKNOWNFOLDERID rfid,
  DWORD            dwFlags,
  HANDLE           hToken,
  PWSTR            *ppszPath
);
```

ILSpy:

```
[DllImport("SHELL32", ExactSpelling = true)]
public unsafe static extern HRESULT SHGetKnownFolderPath(
  [In][Const] Guid* rfid, 
  [In] uint dwFlags, 
  [Optional][In] HANDLE hToken, 
  [Out] ushort** ppszPath);
```

**Comment by kennykerr** [comment] 2021-02-16 06:19
It might be better if we added a first-class WCHAR type rather than relying on ushort plus an attribute. That would seem to be a lot simpler given how ubiquitous such pointer types are. Just a thought.

**Comment by sotteson1** [comment] 2021-02-16 18:34
I've been thinking the same thing. The problem is not all WCHAR* are null terminated, although most are. And some are double null terminated. We have the same problem with single byte strings too. I could follow our handle pattern for these and use attributes if they're not normal null-terminated strings.

**Comment by timsneath** [comment] 2021-02-16 18:47
I suspect we can have our cake and eat it. `WCHAR` is a good general type for Unicode string types, but we can use attributes to more finely delineate between subtypes. 

I'm also wondering (but haven't checked) how we delineate between UTF-8 and ANSI strings, which might both be represented as `Pointer<Utf8>` in a Dart projection, but are different in that only UTF-8 allows variable length encoding.

**Comment by AArnott** [comment] 2021-02-16 18:48
We should not create typedef structs where equivalent ECMA types already exist. We should just use `System.Char` here.

**Comment by AArnott** [comment] 2021-02-16 18:49
Attributes to identify additional traits such as null-termination are fine, but we don't need a custom struct instead of `char` to represent the data type pointed to.

**Comment by kennykerr** [comment] 2021-02-16 18:56
There's a big difference between a `char` and a `LPCWSTR`. The latter implies a null terminated string of 16 bit characters. Having a single handle type for `LPCWSTR` is helpful in avoiding having to always express a pointer to a character that's constant and terminated. 

Also, WinRT metadata already reserves ECMA `char` and `string` to mean a WinRT character and string respectively. These are different to `LPCWSTR` and would make it impossible for language projections to deal with both WinRT and Win32 metadata at the same time.

**Comment by sotteson1** [comment] 2021-02-16 19:14
I'm suggesting we change strings to look like this:

```C#
[NativeTypedef]
public struct WSTR
{
    public char* Value;
}
 
[NativeTypedef]
public struct STR
{
    public byte* Value;
}
```

And then use attributes for things like const or non-null terminated.

**Comment by sotteson1** [comment] 2021-02-18 00:42
Fixed in latest release.

**Closed by sotteson1** 2021-02-18 00:42 UTC
Labels: usability
