### ISSUE TITLE
Variadic functions are not declared as variadic in `windows-sys`

### ISSUE THREAD

**Issue by mtth-bfft** [microsoft/win32metadata#800] opened 2022-02-09 19:55 UTC
The prototypes of variadic functions like `ber_printf`, `DbgPrint` or `DbgPrintEx` in `windows-sys` (at least up to 0.32.0) only contain their fixed arguments (that is, up to the format string):

```C
WINBERAPI INT BERAPI ber_printf(
  [in, out] BerElement *pBerElement,
  [in]      PSTR       fmt,
            ...        
);
```
```rust
pub fn ber_printf(pberelement: *mut berelement, fmt: super::super::Foundation::PSTR) -> i32;
```

Rust does not support variadic functions except for FFI declarations, so it will be impossible to add support for a strongly typed interface in `windows`. However, it would be nice to support C variadic functions in `windows-sys`:

```rust
pub fn ber_printf(pberelement: *mut berelement, fmt: super::super::Foundation::PSTR, ...) -> i32;
```

Without this, these functions are not usable without hardcoding a new prototype for them

**Comment by mikebattista** [comment] 2022-02-14 22:06
I chatted with @sotteson1 and we could add an attribute on variadic functions that projections could then handle. Would that work?

**Comment by mikebattista** [comment] 2022-02-14 22:07
Duplicate of #33.

**Comment by kennykerr** [comment] 2022-02-16 15:42
An attribute on the function would work - Rust can handle C-variadic functions.

**Comment by sotteson1** [comment] 2022-08-29 21:54
Duplicate of #33 as @mikebattista said earlier.

**Closed by sotteson1** 2022-08-29 21:54 UTC
Labels: rust
