### ISSUE TITLE
Functions like `LoadCursorA` need a "DoNotRelease" attribute to indicate the return type should not be freed

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#422] opened 2021-04-15 19:36 UTC

**Comment by AArnott** [comment] 2021-04-17 02:50
Duplicate of #244, but you may want to add the functions you have in mind to that bug.

**Comment by kennykerr** [comment] 2021-04-20 14:12
Steve asked me to add this.

**Comment by AArnott** [comment] 2021-04-20 14:17
Does this mean we're now using *both* options debated in #244?

**Comment by kennykerr** [comment] 2021-04-20 14:27
I think Steve just wanted a reminder to deal with this case as well, but I'm not sure what Steve's decided to do about such cases in general.

**Closed** 2021-04-27 03:40 UTC
Labels: usability
