### ISSUE TITLE
Bug: trait implementations for `TOKEN_GROUPS` are incorrect (and likely for similar structs)

### ISSUE THREAD

**Issue by jantache-microsoft** [microsoft/win32metadata#1377] opened 2022-11-19 10:23 UTC
### Which crate is this about?

windows

### Crate version

0.41.0

### Summary

The generation of the trait derivation code is likely automated, but there should be some exceptions to improve correctness. For this specific case, the `TOKEN_GROUPS` type is used like the C variable payload struct:

```c
struct variable_size_payload {
    header_t header;
    char[] payload
}
```

This means that the automatically derived implementations of traits will behave incorrectly in almost all cases. Thus, I think they should not be derived, so that users are not fooled into thinking they will work.

Example (not using the actual `TOKEN_GROUPS`, but showcases the issue):
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5ed4d46520b2ca69ae163f0c2eb38a45

Note that if `#[derive(Copy, Clone)]` are removed on the first line, the code no longer compiles due to moving out of a raw pointer.

Other links:
https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_token_groups#syntax
https://devblogs.microsoft.com/oldnewthing/20040826-00/?p=38043

**Comment by jantache-microsoft** [comment] 2022-11-21 20:06
I believe the [struct definition in the source](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_token_groups) should be using the `ANYSIZE_ARRAY` definition, perhaps that could be useful if there is access to this info before preprocessor substitution? Otherwise it's an array of size 1, which may also be useful but could have some false positives.

**Comment by mikebattista** [comment] 2023-01-05 19:09
Could you clarify what change you'd like to see in the metadata? Is this something we can scrape or would this be a manual attribution?

**Comment by mikebattista** [comment] 2023-03-16 20:59
Is this a dupe of #912?

**Comment by jantache-microsoft** [comment] 2023-03-16 21:10
I had initially created this ticket in the repo for the Rust bindings and it got transferred here. I'm okay with closing this issue since there's more discussion in the other ticket. However, I'm not sure if there is a ticket tracking the work in this area in the Rust repo anymore - perhaps it should be transferred back, linking to issue 912 as a dependency?

**Comment by mikebattista** [comment] 2023-03-16 21:17
Thanks. Given you mentioned this scenario is `ANYSIZE_ARRAY`, I believe this is a duplicate of #912.

In terms of metadata issues, I will close this one in favor of the duplicate.

**Closed by mikebattista** 2023-03-16 21:17 UTC
Labels: usability
