### ISSUE TITLE
Add metadata for the DISM API

### ISSUE THREAD

**Issue by talagrand** [microsoft/win32metadata#1289] opened 2022-09-30 18:11 UTC
Hi, could you add metadata for the DISM API?
https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism/dism-api-reference?view=windows-11

**Comment by mikebattista** [comment] 2022-10-03 21:15
This API is not in the SDK so would need to be provided by the corresponding kit owner.

**Comment by talagrand** [comment] 2022-10-04 14:14
Is there an example of an existing non-SDK kit that has done this, or instructions on how to go about this?
Is there a risk that types from other kits would conflict with the SDK types?
Could additional metadata for other kits be hosted by this project, or would we need to work with downstream consumers (e.g. Rust for Windows) to either consume additional sources of metadata or split off into additional kit-specific projects?

**Comment by mikebattista** [comment] 2022-10-04 16:08
There are [samples](https://github.com/microsoft/win32metadata/tree/main/sources/GeneratorSdk/samples) in the repo for how to use the [WinmdGenerator](https://www.nuget.org/packages/Microsoft.Windows.WinmdGenerator/) tooling, and the SDK metadata itself in this repo is built with the same tooling. In terms of other Windows kits, the WDK is the first one we are looking at spinning up a repo for (#401) so that the community can build out the metadata. It would be built on all the same tooling.

> Is there a risk that types from other kits would conflict with the SDK types?

Other Windows kits like the WDK depend on the SDK today, so I'd expect the metadata would declare a dependency as well and there should not be conflicts.

> Could additional metadata for other kits be hosted by this project

No. Any other kits would be built out of separate repositories and managed by the corresponding kit owners in conjunction with the community.

> would we need to work with downstream consumers (e.g. Rust for Windows) to either consume additional sources of metadata or split off into additional kit-specific projects?

Our infrastructure is already set up so that projections like Rust can consume additional metadata if the project references a NuGet package built with the WinmdGenerator. I believe the Rust projection already supports this, but yes, in general, projections need to do some work to account for arbitrary metadata references, if they haven't accounted for that yet.

**Comment by talagrand** [comment] 2022-10-04 17:25
Alright, thank you for the help Mike!

**Comment by fgimian** [comment] 2022-10-17 10:26
Thanks for the discussion on this as it is something I'm looking for too.  Can I kindlny ask that we share any further information if anyone gets this working?  I may give it a shot in a few weeks too or fall back to just using Dism.exe if all else fails.

Huge thanks
Fotis

**Comment by mikebattista** [comment] 2023-01-25 22:15
I've recently added an FAQ on this at https://github.com/microsoft/win32metadata/blob/main/docs/faq.md. Also @riverar just posted an article on how he published a metadata-based Rust crate for the DIA SDK at https://withinrafael.com/2023/01/18/generating-metadata-for-the-windows-crate.

Closing out as this will need to be resolved externally.

**Closed by mikebattista** 2023-01-25 22:15 UTC
Labels: enhancement

**Comment by fgimian** [comment] 2024-01-03 04:54
Just in case anyone stumbles across this issue, calling into DISM functions is actually really simple. You'll simply need to reproduce the appropriate structs and functions you need from dismapi.h. I'm not sure if there's any official source for this header, but it can be found in the non-Microsoft [DISMSDK repo](https://github.com/Chuyu-Team/DISMSDK/blob/main/dismapi.h).

As an example in Python, I used [cffi](https://cffi.readthedocs.io/en/stable/) with the following cdefs for the functions I needed (in a module named `winffi.py`):

```python
DISM_CDEFS = """
// These definitions originate from DISMSDK/dismapi.h.
typedef UINT DismSession;

typedef void(*DISM_PROGRESS_CALLBACK)(UINT Current, UINT Total, PVOID UserData);

typedef enum _DismLogLevel {
    DismLogErrors             = 0,
    DismLogErrorsWarnings,
    DismLogErrorsWarningsInfo
} DismLogLevel;

typedef enum _DismPackageIdentifier {
    DismPackageNone = 0,
    DismPackageName,
    DismPackagePath
} DismPackageIdentifier;

typedef enum _DismPackageFeatureState {
    DismStateNotPresent         = 0,
    DismStateUninstallPending,
    DismStateStaged,
    DismStateResolved,
    DismStateRemoved            = DismStateResolved,
    DismStateInstalled,
    DismStateInstallPending,
    DismStateSuperseded,
    DismStatePartiallyInstalled
} DismPackageFeatureState;

typedef enum _DismRestartType {
    DismRestartNo       = 0,
    DismRestartPossible,
    DismRestartRequired
} DismRestartType;

typedef struct _DismCustomProperty {
    PCWSTR Name;
    PCWSTR Value;
    PCWSTR Path;
} DismCustomProperty;

typedef struct _DismFeature {
    PCWSTR                  FeatureName;
    DismPackageFeatureState State;
} DismFeature;

typedef struct _DismFeatureInfo {
    PCWSTR                  FeatureName;
    DismPackageFeatureState FeatureState;
    PCWSTR                  DisplayName;
    PCWSTR                  Description;
    DismRestartType         RestartRequired;
    DismCustomProperty      *CustomProperty;
    UINT                    CustomPropertyCount;
} DismFeatureInfo;

typedef struct _DismString {
    PCWSTR Value;
} DismString;

HRESULT DismInitialize(
    DismLogLevel LogLevel,
    PCWSTR       LogFilePath,
    PCWSTR       ScratchDirectory
);

HRESULT DismShutdown();

HRESULT DismOpenSession(
    PCWSTR      ImagePath,
    PCWSTR      WindowsDirectory,
    PCWSTR      SystemDrive,
    DismSession *Session
);

HRESULT DismCloseSession(
    DismSession Session
);

HRESULT DismGetLastErrorMessage(
    DismString **ErrorMessage
);

HRESULT DismEnableFeature(
    DismSession            Session,
    PCWSTR                 FeatureName,
    PCWSTR                 Identifier,
    DismPackageIdentifier  PackageIdentifier,
    BOOL                   LimitAccess,
    PCWSTR                 *SourcePaths,
    UINT                   SourcePathCount,
    BOOL                   EnableAll,
    HANDLE                 CancelEvent,
    DISM_PROGRESS_CALLBACK Progress,
    PVOID                  UserData
);

HRESULT DismDisableFeature(
    DismSession            Session,
    PCWSTR                 FeatureName,
    PCWSTR                 PackageName,
    BOOL                   RemovePayload,
    HANDLE                 CancelEvent,
    DISM_PROGRESS_CALLBACK Progress,
    PVOID                  UserData
);

HRESULT DismGetFeatures(
    DismSession           Session,
    PCWSTR                Identifier,
    DismPackageIdentifier PackageIdentifier,
    DismFeature           **Feature,
    UINT                  *Count
);

HRESULT DismGetFeatureInfo(
    DismSession           Session,
    PCWSTR                FeatureName,
    PCWSTR                Identifier,
    DismPackageIdentifier PackageIdentifier,
    DismFeatureInfo       **FeatureInfo
);
"""

ffi = FFI()
ffi.cdef(DISM_CDEFS, pack=True)
dismapi = ffi.dlopen("DismAPI.dll")

# Constants originating from DISMSDK/dismapi.h.
DISM_ONLINE_IMAGE = "DISM_{53BFAE52-B167-4E2F-A258-0A37B57FF845}"

def FAILED(hr: int) -> bool:  # noqa: N802
    return hr < 0

def SUCCEEDED(hr: int) -> bool:  # noqa: N802
    return hr >= 0
```

It is critical that you use struct packing for DISM structs to be correctly aligned.

And here's an example of usage using a context manager (to ensure the session is correctly shut down):

```python
from collections.abc import Iterable
from contextlib import AbstractContextManager
from dataclasses import dataclass
from enum import Enum
from types import TracebackType
from typing import Self, cast

from .winffi import DISM_ONLINE_IMAGE, FAILED, SUCCEEDED, dismapi, ffi


class FeatureState(Enum):
    NOT_PRESENT = dismapi.DismStateNotPresent  # type: ignore[attr-defined]
    UNINSTALL_PENDING = dismapi.DismStateUninstallPending  # type: ignore[attr-defined]
    STAGED = dismapi.DismStateStaged  # type: ignore[attr-defined]
    RESOLVED = dismapi.DismStateResolved  # type: ignore[attr-defined]
    REMOVED = dismapi.DismStateRemoved  # type: ignore[attr-defined]
    INSTALLED = dismapi.DismStateInstalled  # type: ignore[attr-defined]
    INSTALL_PENDING = dismapi.DismStateInstallPending  # type: ignore[attr-defined]
    SUPERSEDED = dismapi.DismStateSuperseded  # type: ignore[attr-defined]
    PARTIALLY_INSTALLED = dismapi.DismStatePartiallyInstalled  # type: ignore[attr-defined]


class RestartType(Enum):
    NO = dismapi.DismRestartNo  # type: ignore[attr-defined]
    POSSIBLE = dismapi.DismRestartPossible  # type: ignore[attr-defined]
    REQUIRED = dismapi.DismRestartRequired  # type: ignore[attr-defined]


@dataclass
class FeatureInfo:
    name: str
    state: FeatureState
    display_name: str
    description: str
    restart_required: RestartType


class DISM(AbstractContextManager["DISM"]):
    def __enter__(self) -> Self:
        hr = dismapi.DismInitialize(  # type: ignore[attr-defined]
            dismapi.DismLogErrors,  # type: ignore[attr-defined]
            ffi.NULL,
            ffi.NULL,
        )
        if FAILED(hr):
            self._raise_dism_error(hr)

        self._session = ffi.new("DismSession *")
        hr = dismapi.DismOpenSession(  # type: ignore[attr-defined]
            DISM_ONLINE_IMAGE,
            ffi.NULL,
            ffi.NULL,
            self._session,
        )
        if FAILED(hr):  # pragma: no cover
            self._raise_dism_error(hr)

        return self

    def get_features(self) -> Iterable[tuple[str, FeatureState]]:
        features = ffi.new("DismFeature **")
        count = ffi.new("UINT *")
        hr = dismapi.DismGetFeatures(  # type: ignore[attr-defined]
            self._session[0],
            ffi.NULL,
            dismapi.DismPackageNone,  # type: ignore[attr-defined]
            features,
            count,
        )
        if FAILED(hr):  # pragma: no cover
            self._raise_dism_error(hr)

        for index in range(count[0]):
            yield (
                cast(str, ffi.string(features[0][index].FeatureName)),
                FeatureState(features[0][index].State),
            )

    def get_feature_info(self, name: str) -> FeatureInfo:
        feature_info = ffi.new("DismFeatureInfo **")
        hr = dismapi.DismGetFeatureInfo(  # type: ignore[attr-defined]
            self._session[0],
            name,
            ffi.NULL,
            dismapi.DismPackageNone,  # type: ignore[attr-defined]
            feature_info,
        )
        if FAILED(hr):
            self._raise_dism_error(hr)

        return FeatureInfo(
            name=cast(str, ffi.string(feature_info[0][0].FeatureName)),
            state=FeatureState(feature_info[0][0].FeatureState),
            display_name=cast(str, ffi.string(feature_info[0][0].DisplayName)),
            description=cast(str, ffi.string(feature_info[0][0].Description)),
            restart_required=RestartType(feature_info[0][0].RestartRequired),
        )

    def enable_feature(self, name: str) -> None:
        hr = dismapi.DismEnableFeature(  # type: ignore[attr-defined]
            self._session[0],
            name,
            ffi.NULL,
            dismapi.DismPackageNone,  # type: ignore[attr-defined]
            False,
            ffi.NULL,
            0,
            True,
            ffi.NULL,
            ffi.NULL,
            ffi.NULL,
        )
        if FAILED(hr):
            self._raise_dism_error(hr)

    def disable_feature(self, name: str) -> None:
        hr = dismapi.DismDisableFeature(  # type: ignore[attr-defined]
            self._session[0],
            name,
            ffi.NULL,
            False,
            ffi.NULL,
            ffi.NULL,
            ffi.NULL,
        )
        if FAILED(hr):
            self._raise_dism_error(hr)

    def _raise_dism_error(self, hr: int) -> None:
        last_error_code = hr

        last_error_message_ffi = ffi.new("DismString **")
        hr = dismapi.DismGetLastErrorMessage(  # type: ignore[attr-defined]
            last_error_message_ffi
        )
        if SUCCEEDED(hr):
            last_error_message = ffi.string(last_error_message_ffi[0][0].Value)
        else:
            last_error_message = "An unknown error occurred."

        raise OSError(None, last_error_message, None, last_error_code)

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool | None:
        hr = dismapi.DismCloseSession(self._session[0])  # type: ignore[attr-defined]
        if FAILED(hr):
            self._raise_dism_error(hr)

        hr = dismapi.DismShutdown()  # type: ignore[attr-defined]
        if FAILED(hr):  # pragma: no cover
            self._raise_dism_error(hr)

        return None
```

I have also successfully called into similar APIs in Go and it seems that someone from Microsoft had also created some bindings for Rust several years ago in tho [dismapi-rs repo](https://github.com/jcotton42/dismapi-rs) although this is not on crates. It also uses the winapi crate instead of windows-rs, but that could easily be adapted to use the current Microsoft crate.

I think it would be really great if this was somehow all packaged up into win32metadata as it seems to be the main SDK missing (as far as I can tell) which doesn't seem super logical to someone trying to consume these SDKs. I understand there may be a good explanation for it, but as a user, it just makes things more difficult.

Anyways, hope this helps someone out there
Fotis

**Comment by fgimian** [comment] 2024-03-05 10:53
A little more reference material for those hoping to implement this themselves. Here's an implementation in Rust. I may be publishing this as part of an upcoming open source project depending on how it all turns out. 😄 

**ffi.rs**

```rust
#![allow(
    dead_code,
    non_snake_case,
    non_camel_case_types,
    clippy::upper_case_acronyms,
    clippy::enum_variant_names,
    clippy::module_name_repetitions
)]
use std::{
    ffi::{c_uint, c_void},
    fmt::Debug,
};

use windows::{
    core::{w, HRESULT, PCWSTR},
    Win32::Foundation::{BOOL, HANDLE},
};

type UINT = c_uint;
type VOID = c_void;
type PVOID = *mut c_void;

pub type DismSession = UINT;
pub type DISM_PROGRESS_CALLBACK =
    Option<unsafe extern "C" fn(Current: UINT, Total: UINT, UserData: PVOID)>;

pub const DISM_ONLINE_IMAGE: PCWSTR = w!("DISM_{53BFAE52-B167-4E2F-A258-0A37B57FF845}");

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub enum DismLogLevel {
    DismLogErrors = 0,
    DismLogErrorsWarnings,
    DismLogErrorsWarningsInfo,
}

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub enum DismPackageIdentifier {
    DismPackageNone = 0,
    DismPackageName,
    DismPackagePath,
}

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub enum DismPackageFeatureState {
    DismStateNotPresent = 0,
    DismStateUninstallPending,
    DismStateStaged,
    DismStateRemoved,
    DismStateInstalled,
    DismStateInstallPending,
    DismStateSuperseded,
    DismStatePartiallyInstalled,
}

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub enum DismRestartType {
    DismRestartNo = 0,
    DismRestartPossible,
    DismRestartRequired,
}

#[repr(C, packed)]
#[derive(Copy, Clone, Debug)]
pub struct DismCustomProperty {
    pub Name: PCWSTR,
    pub Value: PCWSTR,
    pub Path: PCWSTR,
}

#[repr(C, packed)]
#[derive(Copy, Clone, Debug)]
pub struct DismFeature {
    pub FeatureName: PCWSTR,
    pub State: DismPackageFeatureState,
}

#[repr(C, packed)]
#[derive(Copy, Clone, Debug)]
pub struct DismFeatureInfo {
    pub FeatureName: PCWSTR,
    pub FeatureState: DismPackageFeatureState,
    pub DisplayName: PCWSTR,
    pub Description: PCWSTR,
    pub RestartRequired: DismRestartType,
    pub CustomProperty: *const DismCustomProperty,
    pub CustomPropertyCount: UINT,
}

#[repr(C, packed)]
#[derive(Copy, Clone, Debug)]
pub struct DismString {
    pub Value: PCWSTR,
}

#[link(name = "dismapi", kind = "raw-dylib")]
extern "C" {
    pub fn DismInitialize(
        LogLevel: DismLogLevel,
        LogFilePath: PCWSTR,
        ScratchDirectory: PCWSTR,
    ) -> HRESULT;

    pub fn DismShutdown() -> HRESULT;

    pub fn DismOpenSession(
        ImagePath: PCWSTR,
        WindowsDirectory: PCWSTR,
        SystemDrive: PCWSTR,
        Session: *mut DismSession,
    ) -> HRESULT;

    pub fn DismCloseSession(Session: DismSession) -> HRESULT;

    pub fn DismGetLastErrorMessage(ErrorMessage: *mut *mut DismString) -> HRESULT;

    pub fn DismDelete(DismStructure: *const VOID) -> HRESULT;

    pub fn DismEnableFeature(
        Session: DismSession,
        FeatureName: PCWSTR,
        Identifier: PCWSTR,
        PackageIdentifier: DismPackageIdentifier,
        LimitAccess: BOOL,
        SourcePaths: *const PCWSTR,
        SourcePathCount: UINT,
        EnableAll: BOOL,
        CancelEvent: HANDLE,
        Progress: DISM_PROGRESS_CALLBACK,
        UserData: PVOID,
    ) -> HRESULT;

    pub fn DismDisableFeature(
        Session: DismSession,
        FeatureName: PCWSTR,
        PackageName: PCWSTR,
        RemovePayload: BOOL,
        CancelEvent: HANDLE,
        Progress: DISM_PROGRESS_CALLBACK,
        UserData: PVOID,
    ) -> HRESULT;

    pub fn DismGetFeatures(
        Session: DismSession,
        Identifier: PCWSTR,
        PackageIdentifier: DismPackageIdentifier,
        Feature: *mut *mut DismFeature,
        Count: *mut UINT,
    ) -> HRESULT;

    pub fn DismGetFeatureInfo(
        Session: DismSession,
        FeatureName: PCWSTR,
        Identifier: PCWSTR,
        PackageIdentifier: DismPackageIdentifier,
        FeatureInfo: *mut *mut DismFeatureInfo,
    ) -> HRESULT;
}
```

**error.rs**

```rust
use std::ptr;

use scopeguard::defer;
use windows::{core::HRESULT, Win32::Foundation::ERROR_NO_UNICODE_TRANSLATION};

use crate::dism::ffi::{DismDelete, DismGetLastErrorMessage};

/// An error object consisting of both an error code as well as a mesasge for debugging.
#[derive(Clone, PartialEq, Eq)]
pub struct Error {
    code: HRESULT,
    message: Option<String>,
}

impl Error {
    /// Creates a new error object with an error code and the last DISM error message.
    pub fn new(code: HRESULT) -> Self {
        let message = unsafe {
            let mut message = ptr::null_mut();
            if DismGetLastErrorMessage(&mut message).is_ok() {
                defer! {
                    let result = DismDelete(message.cast());
                    debug_assert!(result.is_ok());
                }

                let message = (*message).Value;
                message
                    .to_string()
                    .ok()
                    .map(|message| message.trim_end().to_string())
            } else {
                None
            }
        };

        Self { code, message }
    }

    /// The error code describing the error.
    pub const fn code(&self) -> HRESULT {
        self.code
    }

    /// The error message describing the error.
    pub fn message(&self) -> String {
        self.message
            .clone()
            .unwrap_or_else(|| "An unknown error occurred.".to_string())
    }
}

impl std::error::Error for Error {}
unsafe impl Send for Error {}
unsafe impl Sync for Error {}

impl From<std::string::FromUtf16Error> for Error {
    fn from(_: std::string::FromUtf16Error) -> Self {
        Self {
            code: HRESULT::from_win32(ERROR_NO_UNICODE_TRANSLATION.0),
            message: Some(
                "No mapping for the Unicode character exists in the target multi-byte code page."
                    .to_string(),
            ),
        }
    }
}

impl std::fmt::Debug for Error {
    fn fmt(&self, fmt: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut debug = fmt.debug_struct("Error");
        debug
            .field("code", &self.code)
            .field("message", &self.message())
            .finish()
    }
}

impl std::fmt::Display for Error {
    fn fmt(&self, fmt: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        std::write!(fmt, "{} ({})", self.message(), self.code())
    }
}
```

**mod.rs**

```rust
mod error;
mod ffi;

use std::{fmt::Debug, ptr};

use scopeguard::defer;
use windows::{
    core::{IntoParam, Param, PCWSTR},
    Win32::Foundation::{FALSE, HANDLE, TRUE},
};

use self::{
    error::Error,
    ffi::{
        DismCloseSession, DismDisableFeature, DismEnableFeature, DismGetFeatureInfo,
        DismGetFeatures, DismInitialize, DismLogLevel, DismOpenSession, DismPackageFeatureState,
        DismPackageIdentifier, DismRestartType, DismSession, DismShutdown, DISM_ONLINE_IMAGE,
    },
};
use crate::dism::ffi::DismDelete;

pub type Result<T> = std::result::Result<T, Error>;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FeatureState {
    NotPresent,
    UninstallPending,
    Staged,
    Removed,
    Installed,
    InstallPending,
    Superseded,
    PartiallyInstalled,
}

impl From<DismPackageFeatureState> for FeatureState {
    fn from(value: DismPackageFeatureState) -> Self {
        match value {
            DismPackageFeatureState::DismStateNotPresent => Self::NotPresent,
            DismPackageFeatureState::DismStateUninstallPending => Self::UninstallPending,
            DismPackageFeatureState::DismStateStaged => Self::Staged,
            DismPackageFeatureState::DismStateRemoved => Self::Removed,
            DismPackageFeatureState::DismStateInstalled => Self::Installed,
            DismPackageFeatureState::DismStateInstallPending => Self::InstallPending,
            DismPackageFeatureState::DismStateSuperseded => Self::Superseded,
            DismPackageFeatureState::DismStatePartiallyInstalled => Self::PartiallyInstalled,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RestartType {
    No,
    Possible,
    Required,
}

impl From<DismRestartType> for RestartType {
    fn from(value: DismRestartType) -> Self {
        match value {
            DismRestartType::DismRestartNo => Self::No,
            DismRestartType::DismRestartPossible => Self::Possible,
            DismRestartType::DismRestartRequired => Self::Required,
        }
    }
}

#[derive(Debug, PartialEq, Eq)]
pub struct FeatureInfo {
    name: String,
    state: FeatureState,
    display_name: String,
    description: String,
    restart_required: RestartType,
}

pub struct Dism {
    session: u32,
}

// TODO: Implement a custom HRESULT and Result which returns DISM errors.
impl Dism {
    pub fn new() -> Result<Self> {
        unsafe {
            let hr = DismInitialize(DismLogLevel::DismLogErrors, PCWSTR::null(), PCWSTR::null());
            if !hr.is_ok() {
                return Err(Error::new(hr));
            }
        }

        let mut session = DismSession::default();
        unsafe {
            let hr = DismOpenSession(
                DISM_ONLINE_IMAGE,
                PCWSTR::null(),
                PCWSTR::null(),
                &mut session,
            );
            if !hr.is_ok() {
                return Err(Error::new(hr));
            }
        }

        Ok(Self { session })
    }

    pub fn features(&self) -> Result<Vec<(String, FeatureState)>> {
        unsafe {
            let mut dism_features = ptr::null_mut();
            let mut count = 0u32;
            let hr = DismGetFeatures(
                self.session,
                PCWSTR::null(),
                DismPackageIdentifier::DismPackageNone,
                &mut dism_features,
                &mut count,
            );
            if !hr.is_ok() {
                return Err(Error::new(hr));
            }
            defer! {
                let result = DismDelete(dism_features.cast());
                debug_assert!(result.is_ok());
            }

            let dism_features = ptr::slice_from_raw_parts(dism_features, count as _);

            let mut features = Vec::with_capacity(count as _);
            for feature in &*dism_features {
                let name = feature.FeatureName;
                features.push((name.to_string()?, feature.State.into()));
            }
            Ok(features)
        }
    }

    pub fn feature_info(&self, name: impl IntoParam<PCWSTR>) -> Result<FeatureInfo> {
        unsafe {
            let name = name.into_param();

            let mut dism_feature_info = ptr::null_mut();
            let hr = DismGetFeatureInfo(
                self.session,
                name.abi(),
                PCWSTR::null(),
                DismPackageIdentifier::DismPackageNone,
                &mut dism_feature_info,
            );
            if !hr.is_ok() {
                return Err(Error::new(hr));
            }
            defer! {
                let result = DismDelete(dism_feature_info.cast());
                debug_assert!(result.is_ok());
            }

            let name = (*dism_feature_info).FeatureName;
            let display_name = (*dism_feature_info).DisplayName;
            let description = (*dism_feature_info).Description;

            Ok(FeatureInfo {
                name: name.to_string()?,
                state: (*dism_feature_info).FeatureState.into(),
                display_name: display_name.to_string()?,
                description: description.to_string()?,
                restart_required: (*dism_feature_info).RestartRequired.into(),
            })
        }
    }

    pub fn enable_feature(&self, name: impl IntoParam<PCWSTR>) -> Result<()> {
        unsafe {
            let name = name.into_param();
            let hr = DismEnableFeature(
                self.session,
                name.abi(),
                PCWSTR::null(),
                DismPackageIdentifier::DismPackageNone,
                FALSE,
                ptr::null(),
                0,
                TRUE,
                HANDLE::default(),
                None,
                ptr::null_mut(),
            );
            if hr.is_ok() {
                Ok(())
            } else {
                Err(Error::new(hr))
            }
        }
    }

    pub fn disable_feature(&self, name: impl IntoParam<PCWSTR>) -> Result<()> {
        unsafe {
            let name: Param<PCWSTR> = name.into_param();
            let hr = DismDisableFeature(
                self.session,
                name.abi(),
                PCWSTR::null(),
                FALSE,
                HANDLE::default(),
                None,
                ptr::null_mut(),
            );
            if hr.is_ok() {
                Ok(())
            } else {
                Err(Error::new(hr))
            }
        }
    }
}

impl Drop for Dism {
    fn drop(&mut self) {
        unsafe {
            if DismCloseSession(self.session).is_ok() {
                let _ = DismShutdown();
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use rstest::rstest;
    use similar_asserts::assert_eq;
    use windows::core::w;

    use super::*;

    // @pytest.mark.skipif(not shell.IsUserAnAdmin(), reason="requires admin privileges")
    #[rstest]
    fn dism_roundtrip() -> Result<()> {
        let dism = Dism::new()?;

        // Ensure a clean state before the test begins.
        dism.disable_feature(w!("TelnetClient"))?;

        let features = dism.features()?;
        assert!(features.len() > 100);

        dism.enable_feature(w!("TelnetClient"))?;

        assert_eq!(
            dism.feature_info(w!("TelnetClient"))?,
            FeatureInfo {
                name: "TelnetClient".to_string(),
                state: FeatureState::Installed,
                display_name: "Telnet Client".to_string(),
                description: "Allows you to connect to other computers remotely.".to_string(),
                restart_required: RestartType::Possible,
            }
        );
        assert!(dism
            .features()?
            .contains(&("TelnetClient".to_string(), FeatureState::Installed)));

        dism.disable_feature(w!("TelnetClient"))?;

        assert_eq!(
            dism.feature_info(w!("TelnetClient"))?,
            FeatureInfo {
                name: "TelnetClient".to_string(),
                state: FeatureState::Staged,
                display_name: "Telnet Client".to_string(),
                description: "Allows you to connect to other computers remotely.".to_string(),
                restart_required: RestartType::Possible,
            }
        );
        assert!(dism
            .features()?
            .contains(&("TelnetClient".to_string(), FeatureState::Staged)));

        Ok(())
    }

    // @pytest.mark.skipif(not shell.IsUserAnAdmin(), reason="requires admin privileges")
    #[rstest]
    fn dism_get_feature_info_invalid_name() -> Result<()> {
        let dism = Dism::new()?;
        let error = dism.feature_info(w!("Boo123")).unwrap_err();
        assert_eq!(error.message(), "Feature name Boo123 is unknown.");
        Ok(())
    }

    // @pytest.mark.skipif(not shell.IsUserAnAdmin(), reason="requires admin privileges")
    #[rstest]
    fn dism_enable_feature_invalid_name() -> Result<()> {
        let dism = Dism::new()?;
        let error = dism.enable_feature(w!("Boo123")).unwrap_err();
        assert_eq!(error.message(), "Feature name Boo123 is unknown.");
        Ok(())
    }

    // @pytest.mark.skipif(not shell.IsUserAnAdmin(), reason="requires admin privileges")
    #[rstest]
    fn dism_disable_feature_invalid_name() -> Result<()> {
        let dism = Dism::new()?;
        let error = dism.disable_feature(w!("Boo123")).unwrap_err();
        assert_eq!(error.message(), "Feature name Boo123 is unknown.");
        Ok(())
    }
}
```

This code is in a `dism` sub-module in my crate.

Hope this helps someone
Fotis
